num1=int(input("pleas enter first number:"))
num2=int(input("pleas enter second number:"))

print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1>num2)
print(num1<num2)
print(num1//num2)
print(num1%num2)