num1=int(input("enter any number: "))
num2=int(input("enter a nother number: "))

print(num1+num2)
print(num1-num2)
print(num1/num2)
print(num1//num2)
print(num1%num2)
print(num1*num2)
print(f"num1<num2={num1<num2}")
print(f"num1>num2={num1>num2}")